[package]
name = "sensecap-backend"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
log = { workspace = true }
anyhow = { workspace = true }
esp-idf-svc = { workspace = true, features = ["experimental"] }
