[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
runner = "espflash flash --monitor"
linker = "ldproxy"

[env]
ESP_IDF_VERSION = "v5.0"

[unstable]
build-std = ["core", "panic_abort", "alloc"]
build-std-features = ["panic_immediate_abort"]
