[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
runner = "espflash flash --monitor"
linker = "ldproxy"

[env]
ESP_IDF_VERSION = "v5.1.2"
DEP_LV_CONFIG_PATH = "/workspaces/sensecap-indicator-d1/firmware-rust/lvgl-config"

[unstable]
build-std = ["std", "panic_abort"]
