[build]
target = "xtensa-esp32s3-none-elf"

[target.xtensa-esp32s3-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_IDF_VERSION = "v5.0"

[unstable]
build-std = ["core", "panic_abort", "alloc"]
build-std-features = ["panic_immediate_abort"]
